---
- name: Checkout twgit
  git:
    repo=https://github.com/Twenga/twgit.git
    depth=1
    dest={{ home }}/twgit
    version=stable

- name: Compile and install twgit
  sudo_user: vagrant
  sudo: yes
  shell: yes | sudo make install
  args:
    chdir: '{{ home }}/twgit'

- name: Add completion file zshrc
  lineinfile:
    dest={{ home }}/.zshrc
    line="source /home/vagrant/twgit/install/zsh_completion.sh"
    insertafter=EOF


