---
- name: Download Golang binary distribution
  get_url:
      url=https://storage.googleapis.com/golang/{{ go_archive_file }}
      dest={{ home }}/{{ go_archive_file }}
- name: Create ~/opt folder
  file:
      path={{ home }}/opt
      state=directory
- name: Unpack the Go binary distribution
  unarchive:
      copy=no
      src={{ home }}/{{ go_archive_file }}
      dest={{ home }}/opt
      creates={{ home }}/opt/go
- name: Add go path settings in .bashrc
  lineinfile: dest={{ home }}/.bashrc line="{{ item }}" insertafter=EOF
  with_items:
    - 'export GOROOT={{ go_root }}'
    - 'export GOPATH={{ go_path }}'
    - 'export PATH={{ go_root }}/bin:$PATH'
    - 'export PATH={{ go_path }}/bin:$PATH'

- name: Add go path settings in .zshrc
  lineinfile: dest={{ home }}/.zshrc line="{{ item }}" insertafter=EOF
  with_items:
    - 'export GOROOT={{ go_root }}'
    - 'export GOPATH={{ go_path }}'
    - 'export PATH={{ go_root }}/bin:$PATH'
    - 'export PATH={{ go_path }}/bin:$PATH'

- name: Create go code folder
  file:
    dest={{ go_path }}/src/github.com
    state=directory
    recurse=yes
    owner=vagrant
    group=vagrant
- name: Install some nice go packages
  command: >
      go get {{ item }}
  environment:
      GOPATH: "{{ go_path }}"
      GOROOT: "{{ go_root }}"
      PATH: "{{ go_root }}/bin:{{ go_path }}/bin:/usr/bin:/bin"
  with_items:
      - golang.org/x/tools/cmd/oracle
      - github.com/nsf/gocode
      - github.com/tools/godep
      - github.com/rogpeppe/godef
      - github.com/jstemmer/gotags
      - golang.org/x/tools/cmd/goimports
      - bitbucket.org/gotamer/gowatch
      - bitbucket.org/liamstask/goose/cmd/goose
