---
- hosts: all
  sudo: true
  vars:
      home: /home/vagrant
      document_root: /vagrant
  pre_tasks:
    - name: check last APT update time
      apt: update_cache=yes cache_valid_time=86400
    - name: Install stuff from Aptitude
      apt: name={{ item }} state=installed
      with_items:
       - git
       - tig
       - vim
       - gcc
       - gdb
       - cgdb
       - bash-completion # Not included in the docker image
       - make
       - tree
       - htop
       - man-db
       - libssl-dev # used by python2 for SSL checking
       - libffi-dev

  roles:
    - {role: zsh, sudo: false}
    - {role: vim, sudo: false}
